#version: '3.8'
services:
  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${DATASOURCE_URI}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USER}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASS}
    depends_on:
      web_db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  web_db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATASOURCE_USER}
      - POSTGRES_PASSWORD=${DATASOURCE_PASS}
      - POSTGRES_DB=prime_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATASOURCE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: